# Generated by Django 4.1.7 on 2023-03-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_tracker', '0002_alter_userrides_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='moving_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='total_time',
            field=models.IntegerField(),
        ),
    ]
